# Generated by Django 4.2 on 2023-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_activity_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='language',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], max_length=128),
        ),
    ]
