# Generated by Django 4.2 on 2023-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_activity_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
