# Generated by Django 4.2 on 2023-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_activity_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='language',
        ),
        migrations.AddField(
            model_name='activity',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], default='Hindi', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], default='Hindi', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Theater', 'Theater'), ('Story Telling', 'Story Telling'), ('Imporv Theater', 'Imporv Theater')], default='Theater', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], default='Hindi', max_length=128),
        ),
        migrations.AddField(
            model_name='sport',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], default='Hindi', max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Fantacy', 'Fantacy'), ('Classic', 'Classic'), ('Comedy', 'Comedy')], default='Drama', max_length=128),
        ),
    ]
