# Generated by Django 4.2 on 2023-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_event_language_remove_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Comedy Shows', 'Comedy Shows'), ('Workshops', 'Workshops'), ('Music Shows', 'Music Shows'), ('Online Streaming Events', 'Online Streaming Events'), ('Meetups', 'Meetups'), ('Kids', 'Kids')], default='Workshops', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='movie'),
        ),
    ]
