# Generated by Django 4.2 on 2023-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_event_category_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Online Games', 'Online Games'), ('E Sports', 'E Sports'), ('Chess', 'Chess'), ('Football', 'Football')], default='Cricket', max_length=128),
        ),
        migrations.AddField(
            model_name='sport',
            name='prices',
            field=models.CharField(choices=[('Free', 'Free'), ('0 - 500', '0 - 500'), ('501 - 2000', '501 - 2000'), ('Above 2000', 'Above 2000')], default='Free', max_length=128),
        ),
    ]
