# Generated by Django 4.2 on 2023-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_sport_category_sport_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='prices',
            field=models.CharField(choices=[('Free', 'Free'), ('0-500', '0-500'), ('501-2000', '501-2000'), ('Above 2000', 'Above 2000')], default='Free', max_length=128),
        ),
    ]
